# Generated by Django 2.2.6 on 2019-10-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191014_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.Genre'),
        ),
    ]
