# Generated by Django 2.2.6 on 2019-10-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191017_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.TextField(max_length=215),
        ),
    ]
